import Sidebar from '@/components/Sidebar';

export const metadata = {
  title: 'TCC',
  description: 'Generated by create next app',
};


const menuItems = [
  { label: 'All Submissions', href: '/submissions' },
  { label: 'My Submissions', href: '/submissions/mine' },
];

export default function SubmissionsLayout({ children }) {
  return (
    <div className="flex px-2 space-x-4">
      <Sidebar menuItems={menuItems} title="Submissions" title_menu="Submissions Menu"/>
      <span className="md:block hidden border-l border-gray-500"></span>
      {children}
    </div>
  );
}
