import Sidebar from "@/components/Sidebar";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function ProblemLayout({ children, params }) {
  return (
    <div className="flex w-3/4 mx-auto my-8 space-x-4">
      <div className="h-max min-w-64 space-y-4">
        <Sidebar slug={params.productId} />
        <Card>
          <div className="p-3 border-b">
            <Label className="text-md font-bold">Top User by Time</Label>
          </div>
          <div className="table-wrapper p-3">
            <table className="w-full border-separate border-spacing-y-2 text-sm">
              <thead>
                <tr className="text-center">
                  <th>#</th>
                  <th>User</th>
                  <th>Time</th>
                </tr>
              </thead>

              <tbody>
                <tr className="text-center">
                  <td>1</td>
                  <td>Name</td>
                  <td>5ms</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Card>
        <Card>
          <div className="p-3 border-b">
            <Label className="text-md font-bold">Top User by Memory</Label>
          </div>
          <div className="table-wrapper p-3">
            <table className="w-full border-separate border-spacing-y-2 text-sm">
              <thead>
                <tr className="text-center">
                  <th>#</th>
                  <th>User</th>
                  <th>Time</th>
                </tr>
              </thead>

              <tbody>
                <tr className="text-center">
                  <td>1</td>
                  <td>Name</td>
                  <td>5ms</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Card>
      </div>
      {children}
    </div>
  );
}
