import Sidebar from "@/components/Problems/Sidebar";

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};


export default async function ProblemLayout({ children, params }) {

  return (
      <div className="container flex mx-auto my-8 space-x-4">
        <div className="h-max min-w-80 space-y-4">
          <Sidebar slug={params.problemId} />
        </div>
        {children}
      </div>
  );
}
