import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function SubmissionsLayout({ children }) {
  return <AuthContextProvider>{children}</AuthContextProvider>;
}
