import Header from '@/components/Nav';
import { Suspense } from 'react'
import Footer from "@/components/Footer";
import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";

// const inter = inter({ subsets: ["latin"] });

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-[100vh] flex flex-col`}>
        <AuthContextProvider>
          <Header />
          {children}
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
