// import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import Header from '../components/Header';
import Footer from '@/components/Home/Footer';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'TCC',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='p-0'>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
