export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default async function ProblemLayout({ children, params }) {
  return (
      <div className="py-24">
        {children}
      </div>
  );
}
