import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: 'TCC',
  description: 'Generated by create next app',
};

export default function ContestLayout({ children }) {
  return (
  <div className="py-24">{children}</div>
  );
}
