export const metadata = {
  title: 'TCC',
  description: 'Generated by create next app',
};

export default async function ContestLayout({ children }) {
  return (
      <div className="py-24">
        {children}
      </div>
  )
}
