import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function ProblemLayout({ children }) {
  return (
    <div className="flex px-2 space-x-4">
      <Sidebar />
      <span className="md:block hidden border-l border-gray-500"></span>
      {children}
    </div>
  );
}
