import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function ProblemLayout({ children }) {
  return (
    <div className="flex mx-32 space-x-12">
      <Sidebar />
      <span className="border-l border-gray-500"></span>
      {children}
    </div>
  );
}
