import Sidebar from '@/components/Sidebar';

export const metadata = {
  title: 'TCC',
  description: 'Generated by create next app',
};


const menuItems = [
  { label: 'Summary', href: '/user' },
  { label: 'Submission', href: '/user/submission' },
];

export default function UserLayout({ children }) {
  return (
    <div className="flex px-2 space-x-4">
      <Sidebar menuItems={menuItems} title="Profile" title_menu="Profile Menu"/>
      <span className="md:block hidden border-l border-gray-500"></span>
      {children}
    </div>
  );
}
